version: "3.9"
services:
  api_java:
    image: dockreg.el.nist.gov/e3/api:java
    restart: always
    ports:
      - "8080:8080"
    networks:
      - default
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    hostname: postgres