version: "3.6"
services:
  postgres:
    image: postgres:13.3
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: CRuj6oyJJirj6ThnfxV7
      POSTGRES_DB: E3
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - default
#    volumes:
#      - /DATA/e3/postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.9.0
    restart: always
    hostname: rabbitmq
    configs:
      - source: e3_rabbitmq_config
        target: /etc/rabbitmq/rabbitmq.conf
    networks:
      - default

  api:
    image: dockreg.el.nist.gov/e3/api
    restart: always
    environment:
      BROKER_URL: "amqp://admin:password@rabbitmq:5672"
      BACKEND_URL: "rpc://"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - default
      - traefik_net
    command: [
        "wait-for-it/wait-for-it.sh", "postgres:5432", "-t", "0", "--",
        "wait-for-it/wait-for-it.sh", "rabbitmq:5672", "-t", "0", "--",
        "python", "manage.py", "runserver", "0.0.0.0:8000"
    ]
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_net"
        - "traefik.http.routers.e3_router_http.rule=Host(`e3test.el.nist.gov`)"
        - "traefik.http.routers.e3_router_http.entrypoints=web"
        - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.e3_router_http.middlewares=https_redirect"
        - "traefik.http.routers.e3_router_https.rule=Host(`e3test.el.nist.gov`)"
        - "traefik.http.routers.e3_router_https.entrypoints=websecure"
        - "traefik.http.routers.e3_router_https.tls"
        - "traefik.http.services.e3_service.loadbalancer.server.port=8000"

  worker:
    image: dockreg.el.nist.gov/e3/api
    restart: always
    deploy:
      replicas: 1
    environment:
      BROKER_URL: "amqp://admin:password@rabbitmq:5672"
      BACKEND_URL: "rpc://"
      C_FORCE_ROOT: "true"
    depends_on:
      - rabbitmq
    networks:
      - default
    command: [
        "wait-for-it/wait-for-it.sh", "rabbitmq:5672", "-t", "0", "--",
        "celery", "-A", "API", "worker", "-l", "INFO"
    ]

configs:
  e3_rabbitmq_config:
    external: true

networks:
  traefik_net:
    external: true