# Generated by Django 3.2 on 2021-04-29 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysisType', models.CharField(blank=True, max_length=30)),
                ('projectType', models.CharField(max_length=30)),
                ('objToReport', models.JSONField(blank=True, default=dict)),
                ('studyPeriod', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('baseDate', models.DateTimeField(blank=True)),
                ('serviceDate', models.DateTimeField()),
                ('timestepVal', models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinValueValidator(models.DateTimeField(blank=True))])),
                ('timestepComp', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)])), django.core.validators.MinValueValidator(0)])),
                ('outputRealBool', models.BooleanField(blank=True)),
                ('interestRate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dRateReal', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('dRateNom', models.DecimalField(decimal_places=2, max_digits=7)),
                ('inflationRate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Marr', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('reinvestRate', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('incomeRateFed', models.JSONField(blank=True, default=dict)),
                ('incomeRateOther', models.JSONField(blank=True, default=dict)),
                ('location', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
