# Generated by Django 3.2 on 2021-04-29 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='Marr',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysisType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='baseDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='dRateReal',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='incomeRateFed',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='incomeRateOther',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='location',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='objToReport',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='outputRealBool',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='reinvestRate',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='studyPeriod',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='timestepComp',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='timestepVal',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinValueValidator(models.DateTimeField(null=True))]),
        ),
    ]
