# Generated by Django 3.2 on 2021-05-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210525_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalrequiredflows',
            name='altID',
            field=models.IntegerField(default=None),
        ),
    ]
