# Generated by Django 3.2 on 2021-04-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210429_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altID', models.IntegerField()),
                ('altName', models.CharField(max_length=30)),
                ('altBCNList', models.JSONField(default=list, null=True)),
                ('baselineBool', models.BooleanField()),
            ],
        ),
    ]
