# Generated by Django 3.2 on 2021-05-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_totalrequiredflows_altid'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaloptionalflows',
            name='altID',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='totaloptionalflows',
            name='bcnSubType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='totaloptionalflows',
            name='bcnTag',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='totaloptionalflows',
            name='bcnType',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='totaloptionalflows',
            name='quantUnits',
            field=models.CharField(default='dollars', max_length=30),
        ),
        migrations.AddField(
            model_name='totaloptionalflows',
            name='sensBool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='totaloptionalflows',
            name='totTagQ',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totaloptionalflows',
            name='totalTagFlowDisc',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totaloptionalflows',
            name='uncBool',
            field=models.BooleanField(default=False),
        ),
    ]
