# Generated by Django 3.2 on 2021-04-29 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alternative'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcnID', models.IntegerField(null=True, unique=True)),
                ('altID', models.JSONField(default=list, null=True)),
                ('bcnType', models.CharField(max_length=30, null=True)),
                ('bcnSubType', models.CharField(max_length=30)),
                ('bcnName', models.CharField(max_length=30)),
                ('bcnTag', models.JSONField()),
                ('initialOcc', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rvBool', models.BooleanField()),
                ('bcnRealBool', models.BooleanField(null=True)),
                ('bcnInvestBool', models.BooleanField(null=True)),
                ('bcnLife', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('recurBool', models.BooleanField(null=True)),
                ('recurInterval', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('recurVarRate', models.CharField(max_length=30)),
                ('recurVarValue', models.JSONField()),
                ('recurEndDate', models.DateTimeField(auto_now_add=True, validators=[django.core.validators.MinValueValidator(models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]))])),
                ('valuePerQ', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('quant', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('quantVarRate', models.CharField(max_length=30)),
                ('qantVarValue', models.JSONField()),
                ('quantUnit', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
