# Generated by Django 3.2 on 2021-04-29 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_rename_qantvarvalue_bcn_quantvarvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcn',
            name='recurInterval',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bcn',
            name='recurVarRate',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bcn',
            name='recurVarValue',
            field=models.JSONField(null=True),
        ),
    ]
