# Generated by Django 3.2 on 2021-04-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20210429_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcn',
            name='quantVarRate',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bcn',
            name='quantVarValue',
            field=models.JSONField(null=True),
        ),
    ]
