# Generated by Django 3.2 on 2021-04-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20210429_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensitivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalVarBool', models.BooleanField(null=True)),
                ('altID', models.IntegerField(null=True, unique=True)),
                ('bcnID', models.CharField(default='', max_length=30, null=True)),
                ('varName', models.CharField(default='', max_length=30, null=True)),
                ('diffType', models.CharField(default='', max_length=30, null=True)),
                ('diffVal', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
        ),
    ]
