# Generated by Django 3.2 on 2021-04-29 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_sensitivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcn',
            name='bcnLife',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
