# Generated by Django 3.2 on 2021-04-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_bcn_bcnlife'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectVariables', models.JSONField(null=True)),
            ],
        ),
    ]
